//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFInstancingDemoClient.SWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWcfService.ISWcfService")]
    public interface ISWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWcfService/IncrementCount", ReplyAction="http://tempuri.org/ISWcfService/IncrementCountResponse")]
        int IncrementCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWcfService/IncrementCount", ReplyAction="http://tempuri.org/ISWcfService/IncrementCountResponse")]
        System.Threading.Tasks.Task<int> IncrementCountAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISWcfServiceChannel : WCFInstancingDemoClient.SWcfService.ISWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWcfServiceClient : System.ServiceModel.ClientBase<WCFInstancingDemoClient.SWcfService.ISWcfService>, WCFInstancingDemoClient.SWcfService.ISWcfService {
        
        public SWcfServiceClient() {
        }
        
        public SWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int IncrementCount() {
            return base.Channel.IncrementCount();
        }
        
        public System.Threading.Tasks.Task<int> IncrementCountAsync() {
            return base.Channel.IncrementCountAsync();
        }
    }
}
