//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClassLibraryWiindowsclient.DumWcfServiceTcp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DumWcfServiceTcp.IDumWcfService")]
    public interface IDumWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDumWcfService/GetText", ReplyAction="http://tempuri.org/IDumWcfService/GetTextResponse")]
        string GetText();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDumWcfService/GetText", ReplyAction="http://tempuri.org/IDumWcfService/GetTextResponse")]
        System.Threading.Tasks.Task<string> GetTextAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDumWcfService/MultiplyTwoInteger", ReplyAction="http://tempuri.org/IDumWcfService/MultiplyTwoIntegerResponse")]
        int MultiplyTwoInteger(int firstNum, int secondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDumWcfService/MultiplyTwoInteger", ReplyAction="http://tempuri.org/IDumWcfService/MultiplyTwoIntegerResponse")]
        System.Threading.Tasks.Task<int> MultiplyTwoIntegerAsync(int firstNum, int secondNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDumWcfServiceChannel : WcfClassLibraryWiindowsclient.DumWcfServiceTcp.IDumWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DumWcfServiceClient : System.ServiceModel.ClientBase<WcfClassLibraryWiindowsclient.DumWcfServiceTcp.IDumWcfService>, WcfClassLibraryWiindowsclient.DumWcfServiceTcp.IDumWcfService {
        
        public DumWcfServiceClient() {
        }
        
        public DumWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DumWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DumWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DumWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetText() {
            return base.Channel.GetText();
        }
        
        public System.Threading.Tasks.Task<string> GetTextAsync() {
            return base.Channel.GetTextAsync();
        }
        
        public int MultiplyTwoInteger(int firstNum, int secondNum) {
            return base.Channel.MultiplyTwoInteger(firstNum, secondNum);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyTwoIntegerAsync(int firstNum, int secondNum) {
            return base.Channel.MultiplyTwoIntegerAsync(firstNum, secondNum);
        }
    }
}
